[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.partitions = default.csv
lib_deps =
    tzapu/WiFiManager@^2.0.17
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:esp32c6_ota]
platform = espressif32
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.1.183
board_build.flash_size = 4MB
board_build.partitions = default.csv
lib_deps =
    tzapu/WiFiManager@^2.0.17
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
